version: '3.5'

services:

  db:
    image: postgres:14.0-alpine3.14
    restart: always
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "$LOCAL_DATA_DIR:/var/lib/postgresql/data"
      -  ./tagpack/db/tagstore_schema.sql:/docker-entrypoint-initdb.d/tagstore_schema.sql
    ports:
      - 5432:5432
    shm_size: '512mb'
