version: '3.5'

services:

  admin:
    image: dpage/pgadmin4:6.11
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ikna.io
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
      - PGADMIN_LISTEN_PORT=8081
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8083:8081"

  pgwatch:
    image: cybertec/pgwatch2:1.9.0
    depends_on:
      - db
    volumes:
      - pg:/var/lib/postgresql
      - grafana:/var/lib/grafana
      - pw2:/pgwatch2/persistent-config
    ports:
      - "8084:8080"
      - "8085:3000"
    depends_on:
      - db
      - bouncer

volumes:
  pg: {}
  pgtags: {}
  grafana: {}
  pw2: {}
  pgadmin-data: {}

networks:
  default:
    name: tag-packs
    external: true