name: tagpack-tool

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8
  - requests==2.27.1
  - pyyaml==6.0
  - tabulate==0.8.9
  - pytest==7.1.1
  - psycopg2==2.8.6
  - pandas>=1.3.5
  - pyyaml-include
  - GitPython
